== AuthControllerTest

```
회원가입 절차

[email/pwd 등록] -> [개인정보 등록] -> [약관 동의] -> [회원가입 완료]

약관 동의 요청에 대한 응답으로 access_token 발급됩니다.
```
=== 일반 회원가입
==== 정상 회원가입
operation::auth-controller-test/sign-up[snippets="response-fields,http-request,http-response"]
==== 중복 이메일
operation::auth-controller-test/sign-up_exception_duplicate_email[snippets="http-request,http-response"]

==== 개인 정보 등록
operation::auth-controller-test/signup_profile[snippets="http-request,http-response"]
==== 개인 정보 중복 예외
operation::auth-controller-test/signup_profile_exception[snippets="http-request,http-response"]

==== 약관 동의
operation::auth-controller-test/enable_terms[snippets="http-request,http-response"]
==== 약관 동의 중복 예외
operation::auth-controller-test/enable_terms_exception[snippets="http-request,http-response"]

=== 일반 로그인

==== 정상 로그인
operation::auth-controller-test/sign-in[snippets="http-request,http-response"]

==== 비밀번호 오류
operation::auth-controller-test/sign-in_exception_wrong_password[snippets="http-request,http-response"]

==== 이메일 오류
operation::auth-controller-test/sign-in_exception_email_not_found[snippets="http-request,http-response"]

==== 회원가입 완료 전 로그인 요청
``ILLEGAL_JOIN_STATUS`` 일 땐 ``errorContent.payload``에 멤버 ID 포함하여 응답

operation::auth-controller-test/signin_before_join-completed[snippets="http-request,http-response"]