== 댓글 API
### 1. 댓글 등록

[source.html]
POST /comments

#### OK

operation::comment-controller-test/create-comment[snippets="http-request,http-response"]

#### E1 존재하지 않는 토픽 ID

operation::comment-controller-test/create-comment_invalid_topic_exception[snippets="http-request,http-response"]

### 2. 댓글 조회

#### OK - 댓글이 하나 이상 존재
operation::comment-controller-test/get_comments_of_topic[snippets="query-parameters,http-request,http-response"]

#### OK - 댓글이 하나도 없는 상황
operation::comment-controller-test/get_comments_of_topic_empty_comments[snippets="http-request,http-response"]

### 3. 댓글 삭제

#### OK - 멤버 (admin || 댓글 작성자) 에 속할 때
operation::comment-controller-test/delete_comment[snippets="http-request,http-response"]

#### E1 삭제 자격이 없을 때
operation::comment-controller-test/delete_comment_member_cannot_touch[snippets="http-request,http-response"]

### 4. 댓글 좋어요

#### OK

operation::comment-controller-test/like_comment[snippets="query-parameters,http-request,http-response"]

### 5. 댓글 싫어요

#### OK
operation::comment-controller-test/hatee_comment[snippets="query-parameters,http-request,http-response"]
