== 토픽 API
### 1. 토픽 생성

[source.html]
POST /topics

- 회원 가입 기능 개발 후 jwt 헤더에 추가 예정
- 이미지 업로드 위한 S3 세팅 예정

#### OK

operation::topic-controller-test/create-topic[snippets="request-fields,http-request,http-response"]

### 2. 토픽 신고

[source.html]
POST /topics/{topicId}/report

#### OK

operation::topic-controller-test/create-topic-report[snippets="http-request,http-response"]

#### E1. 존재하지 않는 토픽일때
#존재하지 않는 토픽일때, 토픽 사용하는 모든 API에서 응답 형식은 동일#

operation::topic-controller-test/create-topic-report_with-non-existent-topic_-topic-not-found-exception[snippets="http-request,http-response"]

#### E2. 이미 신고한 토픽일때

operation::topic-controller-test/create-topic-report_already-reported_-topic-report-duplicate-exception[snippets="http-request,http-response"]

### 3. 토픽 활성화/비활성화

- 신고가 많이 쌓였거나, 운영 등의 이유로 활성화/비활성화
- TODO: 유저가 자신의 토픽 삭제하는 API는 추가 예정. 전체적인 형태는 비슷할 예정

[source.html]
PATCH /topics/{topicId}/status?active=
비활성화: active=false
활성화: active=true

#### OK

operation::topic-controller-test/deactivate-topic[snippets="http-request,http-response"]

#### E1. 작성자가 아닌 유저가 상태 변경 시도

operation::topic-controller-test/deactivate-topic_by-non-author-user_-illegal-topic-status-change-exception[snippets="http-request,http-response"]

### 4. 투표
[source.html]
POST /topics/{topicId}/vote

#### OK
operation::topic-controller-test/vote-for-topic_by-non-author_success[snippets="http-request,http-response"]

#### E1. 토픽 작성자가 투표
operation::topic-controller-test/vote-for-topic_by-author_throw-exception[snippets="http-request,http-response"]

#### E2. 투표 시간을 미래 시간으로 요청
이건 이상한 데이터 요청 막기 위한 예외처리. 정상 로직에선 볼 일 없을 듯하므로 메시지는 임의로 작성함.

operation::topic-controller-test/vote-for-topic_voted-at-future_throw-exception[snippets="http-request,http-response"]

### 5. 투표 취소
[source.html]
DELETE /topics/{topicId}/vote

#### OK

operation::topic-controller-test/cancel-vote-for-topic_existing-vote_success[snippets="http-request,http-response"]

#### E1. 토픽 작성자가 취소
<<_e1_토픽_작성자가_투표, 4. 투표 - E1>>과 동일

#### E2. 취소 시간을 미래 시간으로 요청
<<_e2_투표_시간을_미래_시간으로_요청, 4. 투표 - E2>>와 동일

#### E3. 투표하지 않은 멤버가 취소 요청
정상 로직에선 볼 일 없을 듯하므로 메시지는 임의로 작성함.

operation::topic-controller-test/cancel-vote-for-topic_non-existing-vote_throw-exception[snippets="http-request,http-response"]