package life.offonoff.ab.util.token;

import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import io.jsonwebtoken.security.SignatureException;
import life.offonoff.ab.exception.auth.token.ExpiredTokenException;
import life.offonoff.ab.exception.auth.token.InvalidSignatureTokenException;
import life.offonoff.ab.exception.auth.token.InvalidTokenException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.security.Key;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import static java.lang.System.*;

@Slf4j
@Service
public class JwtProvider implements TokenProvider {

    private static final SignatureAlgorithm signAlg = SignatureAlgorithm.HS256;
    private static final String CLAIM_MEMBER_ID = "member-id";
    private final String accessSecretKey;
    private final String refreshSecretKey;
    private final Long accessExpiresIn;
    private final Long refreshExpiresIn;

//    private final JwtParser parser;

    public JwtProvider(
            @Value("${ab.auth.token.jwt.secret.access_token}") String accessSecretKey,
            @Value("${ab.auth.token.jwt.secret.refresh_token}") String refreshSecretKey,
            @Value("${ab.auth.token.jwt.time.access_token}") Long accessExpiresIn,
            @Value("${ab.auth.token.jwt.time.refresh_token}") Long refreshExpiresIn
    ) {
        this.accessSecretKey = accessSecretKey;
        this.refreshSecretKey = refreshSecretKey;

        this.accessExpiresIn = accessExpiresIn;
        this.refreshExpiresIn = refreshExpiresIn;

        /* TODO : acccess-token & refresh-token 추상화
        this.parser = Jwts.parserBuilder()
                          .setSigningKey(key(accessSecretKey))
                          .build();
         */
    }

    //== Generate ==//
    @Override
    public String generateAccessToken(Long memberId) {
        return Jwts.builder()
                .setHeader(header())
                .setClaims(payloads(memberId))
                .setExpiration(exp(currentTimeMillis(), accessExpiresIn))
                .signWith(key(accessSecretKey), signAlg)
                .compact();
    }

    @Override
    public String generateRefreshToken(Long memberId) {
        return Jwts.builder()
                .setHeader(header())
                .setClaims(payloads(memberId))
                .setExpiration(exp(currentTimeMillis(), refreshExpiresIn))
                .signWith(key(refreshSecretKey), signAlg)
                .compact();
    }

    private Map<String, Object> header() {
        Map<String, Object> header = new HashMap<>();
        header.put("alg", signAlg.getValue());
        header.put("typ", "JWT");

        return header;
    }

    private Map<String, Object> payloads(Long memberId) {
        Map<String, Object> payloads = new HashMap<>();
        payloads.put("member-id", memberId);

        return payloads;
    }

    private Date exp(long currentTime, Long expiresIn) {
        Date date = new Date();
        date.setTime(currentTime + expiresIn);

        return date;
    }

    private Key key(String secretKey) {
        return Keys.hmacShaKeyFor(secretKey.getBytes());
    }

    //== decode ==//
    @Override
    public Long getMemberIdFromAccessToken(String accessToken) {
        Jws<Claims> jws = parseAccessJws(accessToken); // JWT 중 JWS 사용

        return jws.getBody() // Claims
                  .get(CLAIM_MEMBER_ID, Long.class);
    }

    @Override
    public Long getMemberIdFromRefreshToken(String refreshToken) {
        Jws<Claims> jws = parseRefreshJws(refreshToken);

        return jws.getBody() // Claims
                  .get(CLAIM_MEMBER_ID, Long.class);
    }

    private Jws<Claims> parseAccessJws(String accessToken) {
        JwtParser parser = Jwts.parserBuilder()
                               .setSigningKey(key(accessSecretKey))
                               .build();

        return parseJws(parser, accessToken);
    }
    private Jws<Claims> parseRefreshJws(String refreshToken) {
        JwtParser parser = Jwts.parserBuilder()
                               .setSigningKey(key(refreshSecretKey))
                               .build();

        return parseJws(parser, refreshToken);
    }

    private Jws<Claims> parseJws(JwtParser parser, String token) {
        // TODO 가독성 개선 & List<JwtParser> -> support() 로 파싱할 수 있는지 확인하는 방식으로 변경
        try
        {
            return parser.parseClaimsJws(token);
        }
        catch (SignatureException signatureEx)
        {
            log.error("this Token({}) is not generated by AB", token);
            throw new InvalidSignatureTokenException(signatureEx);
        }
        catch (ExpiredJwtException expiredEx)
        {
            log.error("expired Token({})", token);
            throw new ExpiredTokenException(expiredEx);
        }
        catch (RuntimeException runtimeEx)
        {
            log.error("invalid Token({})", token);
            throw new InvalidTokenException(runtimeEx);
        }
    }
}

